name: Generate Snake

on:
  schedule: # execute every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Snake Animation.
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-contribution-grid-light.svg?color_snake=#87CEEB&color_dots=#F9F6EE,#F0E68C,#FFD700,#FF8C00,#DC143C
            dist/snake-contribution-grid-dark.svg?color_snake=#1E90FF&color_dots=#28282B,#BDB76B,#E1AD01,#CC7722,#B22222
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
