name: Generate Snake

on:
  schedule: # execute every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Snake Animation.
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/volcano.gif?color_snake=#00BFFF&color_dots=#4f1d23,#883439,#d8474e,#e4914c,#f7b85a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
